# Generated by Django 5.0.2 on 2025-10-17 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maestros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_trabajador', models.CharField(max_length=10, unique=True)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('telefono', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('cubiculo', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('area_investigacion', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('materias_impartidas', models.TextField(blank=True, default='Ninguna', null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
