# Generated by Django 5.0.2 on 2025-10-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0002_maestros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
