# Generated by Django 5.0.2 on 2025-10-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0003_alter_alumnos_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestros',
            old_name='numero_trabajador',
            new_name='id_trabajador',
        ),
        migrations.AddField(
            model_name='alumnos',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maestros',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='maestros',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maestros',
            name='update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='materias_impartidas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
