# Generated by Django 5.0.2 on 2025-10-28 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0004_rename_numero_trabajador_maestros_id_trabajador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestros',
            old_name='materias_impartidas',
            new_name='materias_json',
        ),
    ]
