# Generated by Django 5.0.2 on 2025-11-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0005_rename_materias_impartidas_maestros_materias_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.CharField(max_length=20)),
                ('hora_fin', models.CharField(max_length=20)),
                ('lugar', models.CharField(max_length=255)),
                ('publico', models.TextField()),
                ('programa', models.CharField(blank=True, max_length=255, null=True)),
                ('responsable', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cupo', models.IntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
